---
driver:
  name: docker
  use_sudo: false
  customize:
    memory: 1024

provisioner:
  name: chef_zero

verifier:
  name: inspec
  # sudo: false # if 'true' (default) inSpec will run tests as 'root', rather than 'kitchen'
  format: doc

platforms:
  - name: ubuntu-16.04
    driver_config:
      instance_name: kneaddata
  # - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[KneadData::default]
    attributes:
